### ISSUE TITLE
Adding or editing custom fields in Windows Live Writer generates error

### ISSUE THREAD

**Issue by joshkerr** [tominsam/jekyll-metaweblog#4]
- -> /xmlrpc.php
  calling getPostCategories("", "joshkerr", "xxxxxxxx")
  getPostCategories returned []
  192.168.0.31 - - [09/Oct/2011:16:44:22 CDT] "POST /xmlrpc.php HTTP/1.1" 200 125
- -> /xmlrpc.php
  [2011-10-09 16:44:22] ERROR ArgumentError: Bad encoding name 
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/encoding.rb:31:in `encoding='
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/source.rb:55:in`encoding='
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/source.rb:46:in `initialize'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/source.rb:164:in`initialize'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/source.rb:17:in `new'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/source.rb:17:in`create_from'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:139:in `stream='
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:116:in`initialize'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/parsers/streamparser.rb:6:in `new'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/parsers/streamparser.rb:6:in`initialize'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/document.rb:204:in `new'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rexml/document.rb:204:in`parse_stream'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/xmlrpc/parser.rb:717:in `parse'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/xmlrpc/parser.rb:475:in`parseMethodCall'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/xmlrpc/server.rb:311:in `process'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/xmlrpc/server.rb:758:in`service'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:70:in`run'
  /Users/joshkerr/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
  192.168.0.31 - - [09/Oct/2011:16:44:22 CDT] "POST /xmlrpc.php HTTP/1.1" 500 301
- -> /xmlrpc.php

**Comment by tominsam** [comment]
really need the logs on this one - you're posting something that the ruby server can't interpret, but I need debugging to know what it's sending

**Comment by joshkerr** [comment]
Can you give me a hint on how I can send the debugging?  How do I activate it?

## 

Josh Kerr

**Comment by tominsam** [comment]
Apparently there's a menu: Help | About | Show log file
