### ISSUE TITLE
Launching under Windows causes error (path compatibility issue?)

### ISSUE THREAD

**Issue by joshkerr** [tominsam/jekyll-metaweblog#5]
[2011-10-15 16:42:22] INFO  WEBrick 1.3.1
[2011-10-15 16:42:22] INFO  ruby 1.9.2 (2011-07-09) [i386-mingw32]
jm_server.rb:70:in `trap': unsupported signal SIGHUP (ArgumentError)
        from jm_server.rb:70:in`block in <main>'
        from jm_server.rb:69:in `each'
        from jm_server.rb:69:in`<main>'

**Comment by joshkerr** [comment]
Nope.  Windows doesn't support HUP as a termination signal.  This fixed it:

['INT', 'TERM'].each { |signal|
